name: Build and test webdav addon

on:
  push:
    paths:
      - "webdav/**"
    branches:
      - main
  pull_request:
    paths:
      - "webdav/**"
  workflow_dispatch:

env:
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: addon-webdav

permissions:
  contents: read

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}

  build:
    name: Test build ${{ matrix.arch }}
    needs: init
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6

      - name: Build image (test only)
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          context: webdav
          arch: ${{ matrix.arch }}
          image: ${{ matrix.image }}
          image-tags: test
          push: "false"
          version: test
          cosign: "false"
